export const COMMAND_HANDLER_METADATA = 'COMMAND_HANDLER_METADATA';

export const EVENT_HANDLER_METADATA = 'EVENT_HANDLER_METADATA';

export const MICROSERVICE_CONFIG_PROVIDER = 'MICROSERVICE_CONFIG_PROVIDER';

export const SAGA_EVENT_NAME = 'saga.event.addapptables';
