version: 2.1

general:
  branches:
    only:
      - master # list of branches to build
      - develop
      - /feature-.*/
      - /chore-.*/

jobs:
  test:
    working_directory: ~/crafts
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
            name: Restore Yarn Package Cache
            keys:
              - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn 
      - run:
          name: unit test
          command: yarn test
      - run: # run code coverage report
          name: code-coverage
          command: yarn coverage

workflows:
  run-test:
    jobs:
      - test:
          context: addapptables 
