version: 2

jobs:
  build:
    working_directory: ~/crafts
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
            name: Restore Yarn Package Cache
            keys:
              - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn  

  test:
    working_directory: ~/crafts
    machine: true
    steps:
      - checkout
      - run: 
          name: Prepare nvm
          command: |
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo ' [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
      - run: 
          name: Upgrade Node.js
          command: |
            nvm install v12
            node -v
            nvm alias default v12
      - run:
          name: unit test
          command: npm run test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
      